import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./registry";
import { FormProvider } from "@/contexts/FormContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <FormProvider>
          <body className={inter.className} style={{ background: "#fff" }}>
            {children}
          </body>
        </FormProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
